### ISSUE TITLE
[Radionice] Ispraviti podatke u modalu Agile

### ISSUE THREAD

**Issue by filipstev** [djordjemoj/s2s#136]
Ne treba da stoji visual studio

<img width="1440" alt="Screenshot 2022-09-26 at 20 24 08" src="https://user-images.githubusercontent.com/62512535/192352177-69aa648a-dcdf-4240-93b6-6ad7362dd87c.png">

**Comment by filipstev** [comment]
pogresan prvi paragraf, tekst je o radionici iz C-a

**Comment by filipstev** [comment]
obrisati ikonicu za laptop

**Comment by djordjemoj** [comment]
uraddjeno
