### ISSUE TITLE
[Radionice] Ispraviti slovo u Java radionici modalu

### ISSUE THREAD

**Issue by filipstev** [djordjemoj/s2s#137]
treba da bude IntelliJ IDEA 
<img width="1440" alt="Screenshot 2022-09-26 at 20 44 57" src="https://user-images.githubusercontent.com/62512535/192355868-76bee233-f48a-4bb6-9f45-ca45f8d337d7.png">

**Comment by djordjemoj** [comment]
uradjeno bice u sl pushu
