### ISSUE TITLE
[Radionice] Pogresan tekst o predavacu

### ISSUE THREAD

**Issue by filipstev** [djordjemoj/s2s#138]
zameniti tekst sa odgovarajucim (ovaj trenutni je od Mirila)

<img width="1440" alt="Screenshot 2022-09-26 at 20 54 11" src="https://user-images.githubusercontent.com/62512535/192357472-9890c7e3-9676-4037-ac0f-c4ac6d28ff67.png">

**Comment by djordjemoj** [comment]
uradjeno
