### ISSUE TITLE
[Radionice] Ispraviti unity radionicu

### ISSUE THREAD

**Issue by filipstev** [djordjemoj/s2s#140]
Izbaciti Dimitrija i dodati unity kao ekstenziju u potreban softver
<img width="1440" alt="Screenshot 2022-09-26 at 20 58 54" src="https://user-images.githubusercontent.com/62512535/192359522-0af57f20-7814-4f51-a1b0-ab8da5949db6.png">

**Comment by djordjemoj** [comment]
@izbacio dimitrija ali ne razumem ovo za unity, vec je tu i na slici

**Comment by filipstev** [comment]
zajebao sam se, mislio sam unity kao program, laki mi je rekao da treba i VSCode ektsenzija ali i unity kao program
