### ISSUE TITLE
[Modal] Modal ispada van ekrana

### ISSUE THREAD

**Issue by filipstev** [djordjemoj/s2s#141]
Ispraviti da modal bude centriran, kao i da ne moze da se skroluje ceo modal (samo da moze poslednji pasus ako ima potrebe)
<img width="1440" alt="Screenshot 2022-09-26 at 21 09 56" src="https://user-images.githubusercontent.com/62512535/192360199-666e21ec-6518-4ba4-8cce-61646aaaa936.png">

**Comment by djordjemoj** [comment]
done
