### ISSUE TITLE
[Prijava] Alternativna radionica ne treba da bude obavezna

### ISSUE THREAD

**Issue by filipstev** [djordjemoj/s2s#144]
Alternativna radionica ne treba da bude obavezna kao ni sledece pitanje (13)

<img width="1440" alt="Screenshot 2022-09-26 at 21 48 51" src="https://user-images.githubusercontent.com/62512535/192366804-983e7414-a983-40dd-ac32-33a00e32fa44.png">

**Comment by djordjemoj** [comment]
uradjeno
