### ISSUE TITLE
[O nama] Tekst popucao

### ISSUE THREAD

**Issue by filipstev** [djordjemoj/s2s#147]
![WhatsApp Image 2022-09-26 at 10 00 25 PM](https://user-images.githubusercontent.com/62512535/192369251-22ac1a7c-8e32-4ea6-b43b-1823c692a286.jpeg)

**Comment by filipstev** [comment]
telefon - samsung galaxy s21

**Comment by djordjemoj** [comment]
trebalo bi da je sad ok
