### ISSUE TITLE
[FAQ] Dodati link za prijavu u okviru FAQ sekcije

### ISSUE THREAD

**Issue by filipstev** [djordjemoj/s2s#73]
Bilo bi super da ova reč bude link ka formi
![image](https://user-images.githubusercontent.com/62512535/192058530-3e9ec5bf-d578-46c9-8301-e9f0fbc5b1e4.jpeg)

**Comment by djordjemoj** [comment]
Moze isto kao za nav u prijavi, ili kao samo dugme prijava, najbolje preko <a href

**Comment by vajagicb** [comment]
@djordjemoj @filipstev ima li neki update na ovo?
Mislim da smo nesto gledali Filip i ja i da nije moglo da se doda kao link
