### ISSUE TITLE
[Landing] Na svim ekranima postoji s2s logo u gornjem levom uglu, dok po dizajnu ima samo na mobilnom

### ISSUE THREAD

**Issue by filipstev** [djordjemoj/s2s#77]
izbaciti s2s logo u gornjem levom uglu za sve velicine vece od telefona
<img width="1440" alt="Screenshot 2022-09-24 at 00 26 24" src="https://user-images.githubusercontent.com/62512535/192064779-36d07c7f-aab4-4c63-8d6b-f6cb06932f70.png">

**Comment by djordjemoj** [comment]
ovako smo se dogovorili da ostane
