### ISSUE TITLE
[Panel] Slike panelista nemaju border a imaju shadow

### ISSUE THREAD

**Issue by filipstev** [djordjemoj/s2s#80]
Slike panelista bi trebalo da imaju border kao na dizajnu i da nemaju box-shadow

<img width="1440" alt="Screenshot 2022-09-24 at 00 41 01" src="https://user-images.githubusercontent.com/62512535/192065920-9cdee463-64f6-4fd3-b8f6-4ac29db9fe6e.png">

**Comment by djordjemoj** [comment]
resavacemo kad znamo da imamo panel, sad cu ga zakomentarisati
