### ISSUE TITLE
[General] Zameniti <p> tagove sa odgovarujucim heading tagovima

### ISSUE THREAD

**Issue by filipstev** [djordjemoj/s2s#85]
Na raznim mestima se koristi `<p>` tag koji oznacava paragraf, iako je u pitanju naslov
Primer: na landing stranici, naslov "Where learning begins" je `<p>` a trebalo bi da bude odgovarajuci h tag. Izmeniti i na ostalim mestima (nazivi sekcija, partneri itd)

**Comment by vajagicb** [comment]
Promeniću ovo na higher priority issue jer ćemo se bolje indeksirati na Google-u ako se ovo koriguje uskoro. Stavite ovo kao jedan od najviših prioriteta nakon otvaranja prijava jer će nam SEO biti bolji.
