### ISSUE TITLE
[Tim] Fale okviri oko slika 

### ISSUE THREAD

**Issue by filipstev** [djordjemoj/s2s#86]
Dodati crne okvire iz dizajna za slike timova

<img width="1440" alt="Screenshot 2022-09-24 at 01 04 42" src="https://user-images.githubusercontent.com/62512535/192067659-e9008a3c-5ab4-4915-ab6e-cb39cbaa42af.png">

**Comment by djordjemoj** [comment]
ja bih ovo ostavio za kasnije, jer ne znam kako da stavim border na hex slike, sem da menjamo svaku sliku

**Comment by djordjemoj** [comment]
mozda bi moglo jedino da ide pozadinski hexs koji je malo veci od, slike , probacu to

**Comment by vajagicb** [comment]
Može tek nakon otvaranja prijava
