### ISSUE TITLE
[Futer] Drugaciji font u delu kontakt

### ISSUE THREAD

**Issue by filipstev** [djordjemoj/s2s#88]
Font deluje drugacije od dizajna (boja, mozda i debljina), ispraviti da bude kao na dizajnu

<img width="1440" alt="Screenshot 2022-09-24 at 01 11 50" src="https://user-images.githubusercontent.com/62512535/192068169-e9f333eb-11fb-45a3-a8cf-e17897353581.png">

**Comment by djordjemoj** [comment]
obrisi font Family i samo ce postati Default font
