### ISSUE TITLE
[Futer] Boje u futeru nisu kao po dizajnu

### ISSUE THREAD

**Issue by filipstev** [djordjemoj/s2s#90]
Ispraviti boje u futeru za ikonice, heksagone oko ikonica, i generalno boja futera, tacne vrednosti stoje u dizajnu

**Comment by vajagicb** [comment]
Ovo bi trebalo uskoro isto popraviti @djordjemoj 

Ne mora pre otvaranja prijava, to je bitno, ali ako može do petka uveče da bude gotovo
