### ISSUE TITLE
[Tim] Font koordinatora nije dobar

### ISSUE THREAD

**Issue by filipstev** [djordjemoj/s2s#91]
Font kod koordinatora nije tacan (ima neki crni border oko slova cega nema na dizajnu)
<img width="1440" alt="Screenshot 2022-09-24 at 01 18 14" src="https://user-images.githubusercontent.com/62512535/192068556-ef2e6a59-406a-40ff-bc74-a95c12b5e1a0.png">

**Comment by vajagicb** [comment]
Proveriti još jednom iako smo pričali o tome i na sastanku.
