### ISSUE TITLE
[Navbar] Dodati padding gore i dole

### ISSUE THREAD

**Issue by filipstev** [djordjemoj/s2s#93]
Na navbaru nema dovoljno mesta iznad i ispod teksta, dodati mali padding, moze kao na dizajnu

<img width="1440" alt="Screenshot 2022-09-24 at 01 26 01" src="https://user-images.githubusercontent.com/62512535/192069056-443b0e40-1e46-4510-a549-f8d2869d06b5.png">

**Comment by djordjemoj** [comment]
povecao ga za 8px, mislim da je sad bolje
