### ISSUE TITLE
[Landing] Dugme "Prijavi se" se ne vidi na telefonu

### ISSUE THREAD

**Issue by filipstev** [djordjemoj/s2s#94]
Dugme se ne vidi kad se udje na sajt odmah, iphone

![WhatsApp Image 2022-09-23 at 11 44 02 PM](https://user-images.githubusercontent.com/62512535/192069264-77ba8361-4303-40de-a88a-41ef70db451b.jpeg)

**Comment by filipstev** [comment]
telefon iPhone 7

**Comment by djordjemoj** [comment]
podigao sam ga za oko 5%, sad bi trebalo da se vidi i na ajfonu

**Comment by djordjemoj** [comment]
jos malo sam ga podigao
