### ISSUE TITLE
[Navbar] Sekcija na kojoj se nalazimo nije selektovana kada se klikne

### ISSUE THREAD

**Issue by filipstev** [djordjemoj/s2s#95]
Trebalo bi sekcije da budu obojene plavom kad se nalazimo na njima (npr kliknem na radionice, on me odvede na radionice i ostane obojeno u navbaru)

**Comment by vajagicb** [comment]
Pogledati kako je na dizajnu


![Capture](https://user-images.githubusercontent.com/57573829/192143908-bde73714-44d8-4de6-b3c9-4608cc731330.PNG)

**Comment by vajagicb** [comment]
Može da bude u nekom od skorijih push-ova urađeno jer za sad je i dalje samo hover @djordjemoj
